version: "3.8"
services:
  promethes:
    image: prom/prometheus:v2.55.0
    ports:
      - "9090:9090"
    volumes:
      - "./library/prometheus/prometheus.yml:/ext/prometheus/prometheys.yml"
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
